web:
  build: .
  ports:
   - "80:80"
  volumes:
   - ./server/config:/opt/chetbot/server/config:ro
  links:
   - email
email:
  image: chetbox/correo:1.0.1
  volumes:
  - ./server/config:/app/config:ro

